import "server-only";
import { marked } from "marked";
import { sanitizeRenderedHtml } from "@/lib/sanitize";

/**
 * Shared MDX plumbing for the blog + landing-page systems. Posts/pages are
 * clean Markdown + YAML frontmatter in `content/**`; this renders them
 * server-side (zero client JS). The `migrate-site` skill writes content into
 * the `content/blog` + `content/pages` holding areas in exactly this shape.
 *
 * Frontmatter is machine-generated by the migration importer, so a tiny strict
 * parser is safe and keeps the dependency surface to just `marked`.
 */

export const INLINE_CTA_MARKER = "<!--INLINE_CTA-->";

function unquote(v: string): string {
  const s = v.trim();
  if (s.startsWith('"') && s.endsWith('"')) {
    return s.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, "\\");
  }
  return s;
}

function parseArray(v: string): string[] {
  const out: string[] = [];
  const re = /"((?:[^"\\]|\\.)*)"/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(v))) out.push(m[1].replace(/\\"/g, '"').replace(/\\\\/g, "\\"));
  return out;
}

export function parseFrontmatter(raw: string): {
  data: Record<string, string | string[]>;
  body: string;
} {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { data: {}, body: raw };
  const data: Record<string, string | string[]> = {};
  for (const line of m[1].split("\n")) {
    const mm = line.match(/^(\w+):\s*(.*)$/);
    if (!mm) continue;
    data[mm[1]] = mm[2].trim().startsWith("[") ? parseArray(mm[2]) : unquote(mm[2]);
  }
  return { data, body: m[2] };
}

/** Insert inline-CTA markers before section headings; count scales with length
 *  (1 for medium posts, 2 for long). The post page splits on the marker. */
function withCtaMarkers(html: string): string {
  const starts = [...html.matchAll(/<h[23][\s>]/g)].map((m) => m.index ?? 0);
  if (starts.length < 3) return html;
  const pts =
    starts.length >= 6
      ? [starts[Math.floor(starts.length / 3)], starts[Math.floor((starts.length * 2) / 3)]]
      : [starts[Math.floor(starts.length / 2)]];
  let out = html;
  for (const pos of [...pts].sort((a, b) => b - a)) {
    out = out.slice(0, pos) + INLINE_CTA_MARKER + out.slice(pos);
  }
  return out;
}

/**
 * Markdown → HTML (server-side only). Adds lazy-load + async decode + mirrors
 * alt→title, and sets width/height from a dims manifest so images reserve space
 * (no CLS). Optional inline-CTA markers for blog posts.
 *
 * The `dims` manifest is `content/blog/_image-dims.json` — written by
 * `scripts/blog-images.mjs` (`npm run blog:images`) as `{ "/blog/<slug>/<file>": [w, h] }`.
 * An inline image with no dims entry ships without width/height → CLS; the
 * `content:qa` gate flags that case.
 */
export function renderMarkdown(
  body: string,
  dims: Record<string, [number, number]>,
  withCta = false,
): string {
  let html = marked.parse(body, { gfm: true, async: false }) as string;
  html = html.replace(/<img /g, '<img loading="lazy" decoding="async" ');
  html = html.replace(/<img([^>]*?)\salt="([^"]*)"/g, '<img$1 alt="$2" title="$2"');
  html = html.replace(/<img\b[^>]*\bsrc="([^"]+)"[^>]*>/g, (tag, src) => {
    const d = dims[src as string];
    if (!d || /\bwidth=/.test(tag)) return tag;
    return tag.replace(/>$/, ` width="${d[0]}" height="${d[1]}">`);
  });
  if (withCta) html = withCtaMarkers(html);
  return sanitizeRenderedHtml(html);
}

export function readingMinutes(html: string): number {
  const words = html.replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 220));
}
