// GENERATED by scripts/build-photo-manifest.mjs — do not edit by hand.
// Run `npm run photos:build` after adding or replacing a session photograph.
//
// Each entry carries the shipped file's real intrinsic size (so next/image can
// reserve the box and never shift the layout) and a ~20px inline preview of the
// same photograph (so the box is a soft version of the picture rather than a
// hole while the full file decodes).

export interface GeneratedPhoto {
  readonly src: string;
  readonly width: number;
  readonly height: number;
  /** Painted behind the frame so no image ever starts as a grey hole. */
  readonly dominantColor: string;
  /**
   * Pre-cropped wide variant, present only on art-directed keys. The portrait
   * src above stays correct for mobile, where the hero box is portrait too.
   */
  readonly landscape?: {
    readonly srcSet: string;
    readonly src: string;
    readonly width: number;
    readonly height: number;
  };
  /** Responsive widths of the portrait crop, for the narrow branch. */
  readonly portrait?: {
    readonly srcSet: string;
    readonly src: string;
    readonly width: number;
    readonly height: number;
  };
  readonly blurDataURL: string;
}

export const generatedPhotos = {
  EXHERO: {
    src: "/images/_example/example-landscape-hero.webp",
    width: 2400,
    height: 1600,
    dominantColor: "rgb(104 104 120)",
    portrait: {
      srcSet:
        "/images/_example/example-landscape-hero-p640.webp 640w, /images/_example/example-landscape-hero-p828.webp 828w, /images/_example/example-landscape-hero-p1080.webp 1080w",
      src: "/images/_example/example-landscape-hero-p1080.webp",
      width: 1080,
      height: 1350,
    },
    landscape: {
      srcSet:
        "/images/_example/example-landscape-hero-w1200.webp 1200w, /images/_example/example-landscape-hero-w1600.webp 1600w, /images/_example/example-landscape-hero-w2000.webp 2000w, /images/_example/example-landscape-hero-w2400.webp 2400w",
      src: "/images/_example/example-landscape-hero-w2400.webp",
      width: 2400,
      height: 1350,
    },
    blurDataURL:
      "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABQAwCdASoUAA0APwFsrU8rJiQiMAgBYCAJaQC+SBgfzwLe0AD9NAmtp2MZDKv1b+cAEaeQnJc3Ft+AAAA=",
  },
  EX01: {
    src: "/images/_example/example-portrait-one.webp",
    width: 1200,
    height: 1500,
    dominantColor: "rgb(72 72 72)",
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUABkAPwF0rlMrJrMoKAqqYCAJaQDMWAlxQGwoVhdoQAD51orx3pdT9IXdR3B3MVtUGTevS9YPIJYiT6EAAAAA",
  },
  EX02: {
    src: "/images/_example/example-portrait-two.webp",
    width: 1200,
    height: 1500,
    dominantColor: "rgb(104 104 120)",
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoUABkAPwF2s1QrJyS1KAgCoCAJaQDLaA9nyqQfP4FOIAD9GpAyO4rtFmYZwiVnRfFUro/291+zyiAl3AQAAA==",
  },
  EX03: {
    src: "/images/_example/example-portrait-three.webp",
    width: 1200,
    height: 1500,
    dominantColor: "rgb(72 72 72)",
    blurDataURL:
      "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQBACdASoUABkAPwF0r1KrJrOiqAqqcCAJaQDPZAl3dsUqrHohZSQwAAD51oxIF+MwxCzGz5uaq4T3nlj+uO+A5NUAAA==",
  },
  EX04: {
    src: "/images/_example/example-portrait-four.webp",
    width: 1200,
    height: 1500,
    dominantColor: "rgb(56 56 56)",
    blurDataURL:
      "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoUABkAPwF0r1KrJrOiqAqqcCAJaQDM0Al3dttnKoCAAPnWjEgX4z8ApzSKtr+iRxwblK5ZB0lDjR+nxjAL7AAA",
  },
} as const satisfies Record<string, GeneratedPhoto>;

export type PhotoKey = keyof typeof generatedPhotos;
