import type { NextConfig } from "next";
import path from "path";
import { readFileSync } from "node:fs";

const projectRoot = decodeURIComponent(new URL(".", import.meta.url).pathname);

// Migration redirects (old URLs → new). Generated by the `migrate-site` skill;
// both files are empty `[]` by default, so redirects() is a no-op until a
// migration populates them.
function loadRedirects(file: string): { source: string; destination: string; permanent: boolean }[] {
  try {
    return JSON.parse(readFileSync(path.join(projectRoot, file), "utf8"));
  } catch {
    return [];
  }
}

const isDev = process.env.NODE_ENV === "development";

/**
 * Link response headers (RFC 8288) for agent discovery.
 * Lets AI agents auto-discover the site's API surfaces, llms.txt index,
 * and (future) MCP server card without manual config.
 */
const LINK_HEADER = [
  '</.well-known/api-catalog>; rel="api-catalog"',
  '</.well-known/agent.json>; rel="agent"; type="application/json"',
  '</.well-known/agents.json>; rel="agents"; type="application/json"',
  '</.well-known/agent-skills/index.json>; rel="agent-skills"; type="application/json"',
  '</api/openapi.json>; rel="service-desc"; type="application/json"',
  '</llms.txt>; rel="llms-txt"; type="text/plain"',
  '</llms-full.txt>; rel="llms-full-txt"; type="text/plain"',
  '</.well-known/mcp/server-card.json>; rel="mcp-server-card"; type="application/json"',
  '</auth.md>; rel="auth"; type="text/markdown"',
  '</.well-known/ai-catalog.json>; rel="ai-catalog"; type="application/json"',
].join(", ");

const securityHeaders = [
  { key: "Link", value: LINK_HEADER },
  // Markdown content negotiation (proxy.ts) serves different bodies for
  // text/html vs text/markdown at the same URL — the edge cache MUST key on
  // Accept or it serves whichever variant cached first to everyone.
  // Include Next's RSC vary tokens so our Accept signal is not dropped when
  // the framework merges / replaces Vary on App Router responses.
  {
    key: "Vary",
    value:
      "Accept, RSC, Next-Router-State-Tree, Next-Router-Prefetch, Next-Router-Segment-Prefetch",
  },
  { key: "X-Frame-Options", value: "SAMEORIGIN" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "Cross-Origin-Opener-Policy", value: "same-origin" },
  { key: "Cross-Origin-Resource-Policy", value: "same-origin" },
  { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
  {
    key: "Strict-Transport-Security",
    value: "max-age=63072000; includeSubDomains; preload",
  },
  {
    key: "Content-Security-Policy",
    /**
     * Compatibility-focused CSP for a static lead-gen marketing site.
     *
     * Deliberately uses 'unsafe-inline' instead of nonces:
     *   - This site is mostly static prerendered HTML. A nonce CSP forces every
     *     page through dynamic SSR (cookies/headers reads) and breaks edge cache.
     *   - The common embed vendors here (GTM, Typeform, Calendly, YouTube,
     *     Vimeo) all require inline scripts or iframes that fight strict CSP.
     *   - The real threat surface for this kind of site is form abuse + bot
     *     spam, which is covered upstream by rate-limit + Vercel WAF.
     *
     * We keep the strong basics: frame-ancestors 'none', object-src 'none',
     * base-uri 'self', form-action 'self', HSTS, nosniff, frame-options.
     */
    value: [
      "default-src 'self'",
      // dev: unsafe-eval required for React Fast Refresh (webpack HMR uses eval)
      `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ""} https://www.googletagmanager.com https://*.googletagmanager.com https://www.google-analytics.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://connect.facebook.net https://embed.typeform.com https://*.typeform.com https://assets.calendly.com`,
      "style-src 'self' 'unsafe-inline'",    // required: Tailwind v4 inline styles
      `img-src 'self' data: blob: https://www.google-analytics.com https://*.google-analytics.com https://*.googletagmanager.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://*.doubleclick.net https://www.google.com https://www.facebook.com https://*.facebook.com https://*.typeform.com https://*.calendly.com https://i.ytimg.com https://i.vimeocdn.com`,
      `connect-src 'self' https://www.google-analytics.com https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://www.googleadservices.com https://googleads.g.doubleclick.net https://stats.g.doubleclick.net https://www.facebook.com https://*.facebook.com https://*.typeform.com https://calendly.com https://*.calendly.com${isDev ? " ws://localhost:* http://localhost:*" : ""}`,
      "font-src 'self' data: https://assets.calendly.com",
      // Allow common embed iframes (YouTube, Vimeo, Typeform, Calendly).
      // Adding a new vendor? Add its domain here.
      "frame-src 'self' https://*.youtube.com https://*.youtube-nocookie.com https://player.vimeo.com https://*.typeform.com https://calendly.com https://*.calendly.com https://www.googletagmanager.com https://td.doubleclick.net",
      "frame-ancestors 'none'",
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
    ].join("; "),
  },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  outputFileTracingRoot: projectRoot,
  // Build output dir is overridable so a verification build can target a SEPARATE
  // dir (`npm run build:check` → .next-verify) and never clobber the running dev
  // server's `.next`. Dev + real deploy builds keep the default `.next`.
  distDir: process.env.NEXT_DIST_DIR || ".next",

  // ── Performance optimizations (adapted from p2p-react-website) ──
  experimental: {
    // Inline critical CSS into the HTML head instead of a separate request.
    // Eliminates a render-blocking round-trip; ~150-250ms LCP improvement
    // on cold cache. Safe on all Vercel deploys.
    inlineCss: true,
    // Tree-shake barrel imports so we only pay for what we actually use.
    optimizePackageImports: [
      "framer-motion",
      "@next/third-parties",
    ],
  },

  images: {
    /**
     * Cap the ladder and add a step where large phones actually land.
     *
     * Next's default tops out at 3840 and jumps 1200 -> 1920. A 3x iPhone at
     * 100vw needs ~1290px, so it was served 1920 — about 21 MB of DECODED
     * bitmap per photograph. On a gallery page iOS Safari hits its decode-memory
     * ceiling, evicts images, and repaints them black until it can decode again.
     * That is the "black spots" report, and no amount of caching fixes it,
     * because the file is already local: the cost is decoding, not fetching.
     *
     * 1366 serves that same phone at ~11 MB, still oversampled against the
     * 1290 it asked for, so there is no visible quality change. Smaller phones
     * were already well fitted and are untouched. Dropping 3840 caps the
     * worst case on desktop; 2048 stays for hero sharpness on large displays.
     */
    deviceSizes: [640, 750, 828, 1080, 1200, 1366, 1600, 1920, 2048],
    formats: ["image/avif", "image/webp"],
    // Allowed quality values for next/image. Photographer images often use
    // quality=100; Next.js 16 requires every non-default quality to be listed.
    qualities: [75, 90, 100],
    // 30-day cache on Vercel's image optimizer. Photographer images don't
    // change often; long TTL means edge cache survives source image hiccups
    // and most requests bypass the optimizer entirely.
    minimumCacheTTL: 2592000, // 30 days in seconds
    // All images are local (public/) — no remote image hosts needed.
  },

  async redirects() {
    // old → new migration redirects (blog posts, categories, retired pages).
    return [
      ...loadRedirects("lib/blog-redirects.json"),
      ...loadRedirects("lib/page-redirects.json"),
    ];
  },

  async headers() {
    return [
      { source: "/(.*)", headers: securityHeaders },
      /**
       * Let browsers actually KEEP the photographs.
       *
       * Next serves everything under public/ with `max-age=0, must-revalidate`
       * by default, because those filenames are not content-hashed. Correct in
       * general, wrong for a photography site: a gallery page re-requested every
       * image on every view, every back-button and every repeat visit. Responses
       * were fast (they hit the edge) but each round-trip is a chance to fail, and
       * a next/image request that fails renders as blank space, not a broken icon.
       *
       * It also capped the optimizer: images.minimumCacheTTL asks for a long TTL,
       * but /_next/image inherits the upstream ceiling, so it never reached a
       * browser until this rule existed.
       *
       * One day fresh, thirty days stale-while-revalidate: returning visitors
       * paint from disk, a swapped photograph propagates within a day, and nobody
       * waits on a revalidation to see the page.
       */
      {
        source: "/images/:path*",
        headers: [
          {
            key: "Cache-Control",
            value: "public, max-age=86400, stale-while-revalidate=2592000",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
